// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.34438 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>Buchhaltung</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Buchhaltung {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    public partial class Booking {
        
        private List<BookingAccount> accountsField;
        
        private List<BookingYear> yearsField;
        
        private List<BookingJournal> journalField;
        
        private BookingOpenIssues openIssuesField;
        
        public Booking() {
            this.openIssuesField = new BookingOpenIssues();
            this.journalField = new List<BookingJournal>();
            this.yearsField = new List<BookingYear>();
            this.accountsField = new List<BookingAccount>();
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Account", IsNullable=false)]
        public List<BookingAccount> Accounts {
            get {
                return this.accountsField;
            }
            set {
                this.accountsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Year", IsNullable=false)]
        public List<BookingYear> Years {
            get {
                return this.yearsField;
            }
            set {
                this.yearsField = value;
            }
        }
        
        public List<BookingJournal> Journal {
            get {
                return this.journalField;
            }
            set {
                this.journalField = value;
            }
        }
        
        public BookingOpenIssues OpenIssues {
            get {
                return this.openIssuesField;
            }
            set {
                this.openIssuesField = value;
            }
        }
    }
    
    public partial class BookingAccount {
        
        private ushort idField;
        
        private string nameField;
        
        private BookingAccountType typeField;
        
        public ushort ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        public BookingAccountType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    public enum BookingAccountType {
        
        /// <remarks/>
        Assest,
        
        /// <remarks/>
        Income,
        
        /// <remarks/>
        Expense,
        
        /// <remarks/>
        Credit,
        
        /// <remarks/>
        Debit,
    }
    
    public partial class BookingYear {
        
        private ushort nameField;
        
        private uint dateStartField;
        
        private uint dateEndField;
        
        private string closedField;
        
        public ushort Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        public uint DateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
        
        public uint DateEnd {
            get {
                return this.dateEndField;
            }
            set {
                this.dateEndField = value;
            }
        }
        
        public string Closed {
            get {
                return this.closedField;
            }
            set {
                this.closedField = value;
            }
        }
    }
    
    public partial class BookingJournal {
        
        private List<BookingJournalEntry> entryField;
        
        private ushort yearField;
        
        public BookingJournal() {
            this.entryField = new List<BookingJournalEntry>();
        }
        
        public List<BookingJournalEntry> Entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
            }
        }
        
        public ushort Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
    }
    
    public partial class BookingJournalEntry {
        
        private List<object> itemsField;
        
        private uint dateField;
        
        private byte idField;
        
        private byte openingField;
        
        private bool openingFieldSpecified;
        
        public BookingJournalEntry() {
            this.itemsField = new List<object>();
        }
        
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        public uint Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        public byte ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        public byte Opening {
            get {
                return this.openingField;
            }
            set {
                this.openingField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpeningSpecified {
            get {
                return this.openingFieldSpecified;
            }
            set {
                this.openingFieldSpecified = value;
            }
        }
    }
    
    public partial class BookingJournalEntryCredit {
        
        private int valueField;
        
        private ushort accountField;
        
        private string textField;
        
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        public ushort Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    public partial class BookingJournalEntryDebit {
        
        private int valueField;
        
        private ushort accountField;
        
        private string textField;
        
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        public ushort Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    public partial class BookingOpenIssues {
        
        private BookingOpenIssuesEntry entryField;
        
        public BookingOpenIssues() {
            this.entryField = new BookingOpenIssuesEntry();
        }
        
        public BookingOpenIssuesEntry Entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
            }
        }
    }
    
    public partial class BookingOpenIssuesEntry {
        
        private ushort yearField;
        
        private uint dateField;
        
        private byte idField;
        
        private ushort valueField;
        
        private ushort accountField;
        
        private string textField;
        
        public ushort Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        public uint Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        public byte ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        public ushort Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        public ushort Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
}
