//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lg2de.SimpleAccounting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lg2de.SimpleAccounting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting project files (*.acml)|*.acml.
        /// </summary>
        public static string FileDialogFilter {
            get {
                return ResourceManager.GetString("FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account sheets.
        /// </summary>
        public static string Header_AccountSheets {
            get {
                return ResourceManager.GetString("Header_AccountSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahresbilanz.
        /// </summary>
        public static string Header_AnnualBalance {
            get {
                return ResourceManager.GetString("Header_AnnualBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset balances.
        /// </summary>
        public static string Header_AssetBalances {
            get {
                return ResourceManager.GetString("Header_AssetBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string Header_CreateAccount {
            get {
                return ResourceManager.GetString("Header_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account.
        /// </summary>
        public static string Header_EditAccount {
            get {
                return ResourceManager.GetString("Header_EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit booking entry.
        /// </summary>
        public static string Header_EditBooking {
            get {
                return ResourceManager.GetString("Header_EditBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Header_Journal {
            get {
                return ResourceManager.GetString("Header_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new booking entry.
        /// </summary>
        public static string Header_NewBooking {
            get {
                return ResourceManager.GetString("Header_NewBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings changed.
        /// </summary>
        public static string Header_SettingsChanged {
            get {
                return ResourceManager.GetString("Header_SettingsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application shutdown.
        /// </summary>
        public static string Header_Shutdown {
            get {
                return ResourceManager.GetString("Header_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals and balances.
        /// </summary>
        public static string Header_TotalsAndBalances {
            get {
                return ResourceManager.GetString("Header_TotalsAndBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have changed the display language.
        ///You must restart the application to get setting take effect..
        /// </summary>
        public static string Information_CultureChangeRestartRequired {
            get {
                return ResourceManager.GetString("Information_CultureChangeRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been changed.
        ///Do you want to save?.
        /// </summary>
        public static string Question_SaveBeforeProceed {
            get {
                return ResourceManager.GetString("Question_SaveBeforeProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Word_Balance {
            get {
                return ResourceManager.GetString("Word_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Word_Date {
            get {
                return ResourceManager.GetString("Word_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Word_Total {
            get {
                return ResourceManager.GetString("Word_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various.
        /// </summary>
        public static string Word_Various {
            get {
                return ResourceManager.GetString("Word_Various", resourceCulture);
            }
        }
    }
}
